name: Run Prompt Evaluation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  evaluate-prompts:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 🛠 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install promptfoo python-dotenv openai

      - name: 🔑 Set up API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: 🧪 Run Prompt Evaluation
        run: |
          mkdir -p reports
          promptfoo eval --out ./reports/evaluation_report.html

      - name: 📤 Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-report
          path: reports/evaluation_report.html
